import "./globals.css";

import { Geist, Geist_Mono } from "next/font/google";

import Header from "@/components/layout/Header";
import { NextIntlClientProvider } from "next-intl";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
   const cookieStore = await cookies();
  const localeCookie = cookieStore.get("NEXT_LOCALE");
  const locale = localeCookie?.value || "en";

  const dir = locale === "fa" ? "rtl" : "ltr";
  const messages = await import(`../i18n/locales/${locale}.json`).then(
    (mod) => mod.default || mod
  );

  return (
    <html lang={locale} dir={dir}>
      <NextIntlClientProvider messages={messages} locale={locale}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
        >
          <Header />
          {children}
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
